name: Linux

on:
  push:
    branches:
      - "**"
  pull_request:
    branches: [master]

# To cancel a currently running workflow from the same PR, branch, or tag
# when a new workflow is triggered.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          sudo apt-get install gcc libncursesw5-dev libx11-dev

      - name: Build with ncurses and X11 support
        run: |
          cd src
          make -f Makefile.std -j$(nproc)

  release-build:
    name: Linux Release Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          #sudo apt-get update
          sudo apt-get install gcc libncursesw5-dev libx11-dev

      - name: Build with release flags
        run: |
          cd src
          make -f Makefile.std OPT="-O2" -j$(nproc)
          mv sil ../sil

      - name: Verify build
        run: |
          ls -la sil
          file sil

      - name: Remove outdated PDF manuals
        run: |
          rm lib/docs/*.pdf

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: Sil-Q-linux-x86_64
          # IMPORTANT: Do NOT use quotes to escape spaces in filenames.
          path: |
            sil
            lib
            LICENSE.md
            README.md
            Sil-Q v1.5.0.pdf

